/* HOKAGE — guides: the sensei's demonstration scrolls.
   One guide per distinct step (matched by name; explicit ids win), each with an ink-brush figure or object
   illustration, a four-line how, the one mistake that ruins it, and a reference link.
   Pure lookup + SVG strings. No DOM writes. */
(function (G) {
  'use strict';

  /* ================= the ink figure ================= */
  var INK = 'currentColor', ACC = 'var(--gd-acc)';
  function ln(a, b, w, op) { return '<path d="M' + a[0] + ' ' + a[1] + ' L' + b[0] + ' ' + b[1] + '" stroke="' + INK + '" stroke-width="' + w + '" stroke-linecap="round" fill="none"' + (op ? ' opacity="' + op + '"' : '') + '/>'; }
  function limb(a, b, c, w, op) { return '<path d="M' + a[0] + ' ' + a[1] + ' L' + b[0] + ' ' + b[1] + ' L' + c[0] + ' ' + c[1] + '" stroke="' + INK + '" stroke-width="' + w + '" stroke-linecap="round" stroke-linejoin="round" fill="none"' + (op ? ' opacity="' + op + '"' : '') + '/>'; }
  function head(p, r) { r = r || 11; return '<circle cx="' + p[0] + '" cy="' + p[1] + '" r="' + r + '" fill="' + INK + '"/><circle cx="' + (p[0] - r * .3) + '" cy="' + (p[1] - r * .35) + '" r="' + (r * .28) + '" fill="#fff" opacity=".14"/>'; }
  function ground(y, x1, x2) { return '<line x1="' + (x1 == null ? 14 : x1) + '" y1="' + y + '" x2="' + (x2 == null ? 226 : x2) + '" y2="' + y + '" stroke="' + INK + '" stroke-width="2" opacity=".28" stroke-linecap="round"/>'; }
  function shadow(x, y, rx) { return '<ellipse cx="' + x + '" cy="' + y + '" rx="' + (rx || 40) + '" ry="4" fill="' + INK + '" opacity=".08"/>'; }
  function arrow(d) { return '<path d="' + d + '" fill="none" stroke="' + ACC + '" stroke-width="2.6" stroke-linecap="round" marker-end="url(#ga)"/>'; }
  function tag(x, y, s, anchor) { return '<text x="' + x + '" y="' + y + '" class="gd-t"' + (anchor ? ' text-anchor="' + anchor + '"' : '') + '>' + s + '</text>'; }
  function wall(x, y1, y2) { return '<line x1="' + x + '" y1="' + y1 + '" x2="' + x + '" y2="' + y2 + '" stroke="' + INK + '" stroke-width="5" opacity=".5" stroke-linecap="round"/>'; }
  var DEFS = '<defs><marker id="ga" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="4.5" markerHeight="4.5" orient="auto-start-reverse"><path d="M2 1L8 5L2 9" fill="none" stroke="' + ACC + '" stroke-width="2"/></marker></defs>';
  function svg(body, h) { return '<svg viewBox="0 0 240 ' + (h || 180) + '" class="gd-svg" aria-hidden="true">' + DEFS + body + '</svg>'; }

  /* a figure: h head · n neck · s shoulder · hp hip · L [[knee,ankle,toe?],[…]] · A [[elbow,wrist],[…]]
     index 1 of L/A is the far limb (drawn behind, lighter). Torso is n→hp. */
  function fig(p) {
    var out = '', far = .42;
    if (p.L && p.L[1]) out += limb(p.hp, p.L[1][0], p.L[1][1], 9, far) + (p.L[1][2] ? ln(p.L[1][1], p.L[1][2], 8, far) : '');
    if (p.A && p.A[1]) out += limb(p.s, p.A[1][0], p.A[1][1], 8, far);
    out += ln(p.n, p.hp, 13);
    if (p.L && p.L[0]) out += limb(p.hp, p.L[0][0], p.L[0][1], 9) + (p.L[0][2] ? ln(p.L[0][1], p.L[0][2], 8) : '');
    if (p.A && p.A[0]) out += limb(p.s, p.A[0][0], p.A[0][1], 8);
    out += head(p.h, p.r);
    return out;
  }

  /* ---------- pose library ---------- */
  var P = {
    stand: function () { return ground(164) + shadow(120, 164, 30) + fig({ h: [120, 30], n: [120, 44], s: [120, 52], hp: [121, 96], L: [[[123, 131], [124, 163], [136, 163]], [[116, 131], [115, 163], [103, 163]]], A: [[[126, 76], [131, 100]], [[113, 76], [109, 100]]] }); },
    standArrow: function () { return P.stand() + arrow('M120 20 L120 8') + tag(130, 14, 'crown up'); },
    pushup: function () { return ground(126, 20, 226) + fig({ h: [46, 92], n: [60, 96], s: [66, 98], hp: [140, 100], L: [[[178, 105], [212, 112], [224, 122]], [[176, 108], [210, 116]]], A: [[[52, 114], [50, 126]], [[74, 114], [76, 126]]] }) + arrow('M100 78 L100 66') + tag(110, 72, 'one line, hips level'); },
    pushupFail: function () { return P.pushup() + '<path d="M126 94 Q140 112 156 98" fill="none" stroke="' + ACC + '" stroke-width="2.2" stroke-dasharray="4 4"/>' + tag(150, 128, 'sag = stop', 'end'); },
    pike: function () { return ground(150, 20, 226) + fig({ h: [64, 122], n: [74, 110], s: [78, 104], hp: [132, 58], L: [[[168, 96], [190, 148], [204, 150]], [[172, 100], [194, 150]]], A: [[[64, 128], [58, 150]], [[76, 130], [72, 150]]] }) + arrow('M132 46 L132 30') + tag(140, 36, 'hips high'); },
    squat: function () { return ground(164) + shadow(125, 164, 34) + fig({ h: [108, 38], n: [116, 50], s: [120, 58], hp: [102, 108], L: [[[148, 118], [136, 163], [154, 163]], [[142, 122], [130, 163]]], A: [[[152, 74], [184, 72]], [[150, 78], [180, 78]]] }) + arrow('M78 84 Q66 104 80 122') + tag(24, 96, 'hips back,') + tag(24, 110, 'then down'); },
    deepSquat: function () { return ground(164) + shadow(126, 164, 34) + fig({ h: [122, 62], n: [124, 74], s: [124, 82], hp: [110, 126], L: [[[156, 132], [138, 163], [158, 163]], [[150, 136], [130, 163]]], A: [[[136, 108], [150, 128]], [[130, 110], [144, 130]]] }) + arrow('M188 128 L170 138') + tag(196, 124, 'elbows pry', 'end'); },
    wallsit: function () { return ground(164) + wall(196, 30, 164) + fig({ h: [176, 48], n: [180, 60], s: [180, 68], hp: [178, 116], L: [[[130, 118], [130, 163], [146, 163]], [[126, 122], [124, 163]]], A: [[[184, 92], [186, 114]], [[176, 92], [174, 114]]] }) + arrow('M112 118 L112 100') + tag(60, 92, 'thighs level'); },
    lunge: function () { return ground(164) + shadow(120, 164, 50) + fig({ h: [116, 34], n: [118, 46], s: [118, 54], hp: [118, 100], L: [[[152, 130], [150, 163], [168, 163]], [[86, 130], [58, 164]]], A: [[[124, 78], [128, 100]], [[112, 78], [108, 100]]] }) + arrow('M86 148 L86 160') + tag(30, 150, 'knee kisses'); },
    revLunge: function () { return P.lunge() + arrow('M60 120 L36 120') + tag(30, 110, 'step back', 'start'); },
    plank: function () { return ground(124, 20, 226) + fig({ h: [46, 92], n: [60, 96], s: [66, 98], hp: [140, 100], L: [[[178, 104], [212, 110], [224, 122]], [[176, 107], [210, 114]]], A: [[[60, 122], [44, 122]], [[70, 122], [56, 122]]] }) + arrow('M104 80 L104 66') + tag(112, 72, 'ribs down, glutes on'); },
    sidePlank: function () { return ground(150, 20, 226) + fig({ h: [52, 72], n: [66, 80], s: [72, 84], hp: [140, 106], L: [[[180, 124], [220, 144]], [[176, 128], [216, 148]]], A: [[[66, 120], [60, 150]], [[80, 66], [86, 40]]] }) + arrow('M120 82 L128 66') + tag(134, 72, 'hips up, one line'); },
    hollow: function () { return ground(152, 20, 226) + fig({ h: [58, 96], n: [70, 108], s: [76, 112], hp: [130, 140], L: [[[176, 126], [214, 112]], [[178, 130], [216, 118]]], A: [[[52, 92], [30, 76]], [[60, 92], [40, 78]]] }) + arrow('M130 128 L130 116') + tag(110, 110, 'low back welded down'); },
    deadbug: function () { return ground(152, 20, 226) + fig({ h: [56, 132], n: [70, 136], s: [76, 138], hp: [140, 142], L: [[[152, 108], [200, 116]], [[150, 112], [154, 78]]], A: [[[84, 116], [64, 88]], [[90, 118], [120, 100]]] }) + arrow('M104 128 L104 138') + tag(112, 128, 'back pinned'); },
    superman: function () { return ground(150, 20, 226) + fig({ h: [40, 114], n: [56, 124], s: [62, 128], hp: [138, 138], L: [[[178, 132], [216, 122]], [[176, 136], [214, 128]]], A: [[[42, 112], [18, 100]], [[48, 116], [24, 106]]] }) + arrow('M100 132 L100 118') + tag(110, 122, 'chest + thighs up'); },
    bridge: function () { return ground(150, 20, 226) + fig({ h: [40, 138], n: [56, 136], s: [62, 132], hp: [124, 96], L: [[[160, 108], [164, 150]], [[156, 112], [160, 150]]], A: [[[90, 142], [120, 150]], [[86, 144], [116, 150]]] }) + arrow('M124 84 L124 68') + tag(132, 76, 'squeeze at the top'); },
    mtnClimber: function () { return ground(126, 20, 226) + fig({ h: [46, 92], n: [60, 96], s: [66, 98], hp: [140, 100], L: [[[104, 118], [112, 126]], [[178, 108], [212, 116]]], A: [[[52, 114], [50, 126]], [[74, 114], [76, 126]]] }) + arrow('M148 84 L112 84') + tag(150, 76, 'drive the knee'); },
    burpee: function () { return ground(164) + fig({ h: [78, 24], n: [78, 36], s: [78, 44], hp: [78, 86], L: [[[80, 120], [78, 152], [88, 154]], [[74, 122], [72, 154]]], A: [[[72, 22], [66, 4]], [[84, 22], [90, 4]]] }) + '<g opacity=".45">' + fig({ h: [138, 130], n: [150, 134], s: [156, 136], hp: [200, 140], L: [[[222, 148], [232, 162]], [[220, 150], [230, 164]]], A: [[[150, 152], [148, 164]], [[162, 152], [164, 164]]], r: 8 }) + '</g>' + arrow('M118 150 Q104 118 90 100') + tag(120, 112, 'down, up, jump'); },
    deadhang: function () { return '<line x1="40" y1="18" x2="200" y2="18" stroke="' + INK + '" stroke-width="5" opacity=".6" stroke-linecap="round"/>' + fig({ h: [120, 62], n: [120, 74], s: [120, 80], hp: [120, 124], L: [[[123, 152], [126, 176]], [[117, 152], [114, 176]]], A: [[[104, 48], [104, 20]], [[136, 48], [136, 20]]] }) + arrow('M156 96 L156 126') + tag(164, 114, 'let it lengthen'); },
    jumpingJack: function () { return ground(164) + fig({ h: [120, 26], n: [120, 38], s: [120, 46], hp: [120, 92], L: [[[142, 126], [158, 162], [172, 162]], [[98, 126], [82, 162], [68, 162]]], A: [[[148, 30], [166, 8]], [[92, 30], [74, 8]]] }) + arrow('M66 132 L46 132') + arrow('M174 132 L194 132'); },
    sprint: function () { return ground(164) + fig({ h: [138, 36], n: [132, 48], s: [128, 56], hp: [104, 100], L: [[[142, 124], [136, 162], [150, 158]], [[70, 116], [42, 130]]], A: [[[156, 72], [176, 52]], [[92, 72], [80, 98]]] }) + arrow('M160 130 L204 130') + tag(178, 148, 'drive'); },
    walk: function () { return ground(164) + fig({ h: [120, 30], n: [120, 44], s: [120, 52], hp: [118, 96], L: [[[136, 130], [146, 163], [160, 163]], [[104, 130], [92, 163]]], A: [[[112, 78], [98, 96]], [[130, 78], [140, 96]]] }) + tag(150, 60, 'nose breathing'); },
    aSkip: function () { return ground(164) + fig({ h: [120, 30], n: [120, 44], s: [120, 52], hp: [118, 96], L: [[[152, 106], [146, 138], [160, 134]], [[112, 130], [108, 162], [122, 162]]], A: [[[136, 74], [130, 52]], [[102, 76], [98, 96]]] }) + arrow('M152 90 L152 76') + tag(160, 84, 'knee up, tall'); },
    pogo: function () { return ground(164) + shadow(120, 164, 24) + fig({ h: [120, 22], n: [120, 36], s: [120, 44], hp: [120, 90], L: [[[122, 124], [124, 152], [134, 156]], [[118, 124], [116, 152], [106, 156]]], A: [[[124, 68], [128, 92]], [[116, 68], [112, 92]]] }) + arrow('M160 150 L160 126') + tag(168, 140, 'stiff ankles'); },
    armCircles: function () { return P.stand() + '<path d="M150 62 a24 24 0 1 1 -1 0" fill="none" stroke="' + ACC + '" stroke-width="2.4" stroke-dasharray="3 5"/>' + '<path d="M90 62 a24 24 0 1 0 1 0" fill="none" stroke="' + ACC + '" stroke-width="2.4" stroke-dasharray="3 5"/>'; },
    legSwing: function () { return ground(164) + wall(48, 40, 164) + fig({ h: [100, 30], n: [100, 44], s: [100, 52], hp: [102, 96], L: [[[136, 120], [160, 140]], [[102, 130], [102, 163], [114, 163]]], A: [[[74, 70], [50, 78]], [[110, 78], [116, 100]]] }) + arrow('M124 150 Q150 172 180 144'); },
    overheadReach: function () { return ground(164) + shadow(120, 164, 28) + fig({ h: [120, 42], n: [120, 56], s: [120, 64], hp: [120, 106], L: [[[122, 136], [124, 163], [136, 163]], [[118, 136], [116, 163], [104, 163]]], A: [[[126, 38], [124, 10]], [[114, 38], [116, 10]]] }) + arrow('M156 60 L156 34') + tag(164, 50, 'ribs tall'); },
    fists: function () { return ground(164) + fig({ h: [120, 44], n: [120, 58], s: [120, 66], hp: [120, 108], L: [[[124, 138], [128, 163], [140, 163]], [[116, 138], [112, 163], [100, 163]]], A: [[[142, 46], [150, 18]], [[104, 76], [100, 98]]] }) + arrow('M170 40 L170 12') + tag(120, 176, 'slow, full intent', 'middle'); },
    shake: function () { return ground(164) + fig({ h: [120, 30], n: [120, 44], s: [120, 52], hp: [120, 96], L: [[[128, 130], [130, 163], [142, 163]], [[112, 130], [108, 163], [96, 163]]], A: [[[148, 74], [160, 96]], [[92, 74], [80, 96]]] }) + '<path d="M158 108 q4 6 -2 12 q-4 6 2 12" fill="none" stroke="' + ACC + '" stroke-width="2.4"/><path d="M82 108 q-4 6 2 12 q4 6 -2 12" fill="none" stroke="' + ACC + '" stroke-width="2.4"/>' + tag(120, 176, 'loose everything', 'middle'); },
    calfRaise: function () { return ground(164) + shadow(120, 164, 26) + fig({ h: [120, 26], n: [120, 40], s: [120, 48], hp: [120, 92], L: [[[122, 126], [124, 152], [134, 160]], [[118, 126], [116, 152], [106, 160]]], A: [[[124, 72], [128, 96]], [[116, 72], [112, 96]]] }) + arrow('M156 158 L156 138') + tag(120, 176, 'up slow, down slower', 'middle'); },
    chinTuck: function () { return ground(164) + wall(192, 20, 164) + fig({ h: [166, 40], n: [172, 54], s: [174, 62], hp: [176, 106], L: [[[178, 136], [180, 163], [168, 163]], [[174, 136], [172, 163]]], A: [[[176, 84], [180, 106]], [[172, 84], [168, 106]]] }) + arrow('M120 40 L150 40') + tag(30, 34, 'glide straight back —') + tag(30, 48, 'double chin, not a nod'); },
    wallAngel: function () { return wall(64, 16, 164) + ground(164) + fig({ h: [80, 30], n: [80, 44], s: [80, 52], hp: [80, 96], L: [[[82, 130], [84, 163], [96, 163]], [[78, 130], [76, 163]]], A: [[[104, 40], [104, 12]], [[102, 44], [100, 16]]] }) + '<g opacity=".4">' + limb([80, 52], [104, 62], [104, 88], 8) + '</g>' + arrow('M126 84 L126 36') + tag(134, 60, 'slide, stay on the wall'); },
    doorway: function () { return '<path d="M60 14 V164 M180 14 V164 M60 14 H180" stroke="' + INK + '" stroke-width="5" opacity=".45" fill="none"/>' + ground(164) + fig({ h: [120, 42], n: [120, 56], s: [120, 64], hp: [118, 106], L: [[[142, 134], [152, 163], [166, 163]], [[104, 134], [92, 163]]], A: [[[92, 60], [62, 56]], [[148, 60], [178, 56]]] }) + arrow('M120 130 L120 150') + tag(120, 176, 'step through, chest open', 'middle'); },
    neckRoll: function () { return P.stand() + '<path d="M90 30 Q120 62 150 30" fill="none" stroke="' + ACC + '" stroke-width="2.6" marker-end="url(#ga)"/>' + tag(120, 176, 'ear to ear across the chest — never the back arc', 'middle'); },
    neckIso: function () { return ground(164) + fig({ h: [120, 38], n: [120, 52], s: [120, 60], hp: [120, 104], L: [[[122, 136], [124, 163], [136, 163]], [[118, 136], [116, 163]]], A: [[[148, 66], [134, 40]], [[112, 84], [110, 106]]] }) + arrow('M100 38 L112 38') + tag(24, 42, 'push;') + tag(24, 56, 'neck refuses'); },
    catcow: function () { return ground(150, 20, 226) + fig({ h: [46, 92], n: [60, 84], s: [68, 80], hp: [150, 80], L: [[[150, 118], [200, 120], [216, 148]], [[146, 122], [196, 124]]], A: [[[64, 116], [60, 150]], [[76, 116], [74, 150]]] }) + '<path d="M78 66 Q110 46 144 68" fill="none" stroke="' + ACC + '" stroke-width="2.4" stroke-dasharray="4 4"/><path d="M78 92 Q110 112 144 92" fill="none" stroke="' + ACC + '" stroke-width="2.4" stroke-dasharray="4 4"/>' + tag(110, 40, 'exhale round'); },
    wristRock: function () { return ground(150, 20, 226) + fig({ h: [46, 92], n: [60, 84], s: [68, 80], hp: [150, 84], L: [[[150, 120], [200, 122], [216, 148]], [[146, 124], [196, 126]]], A: [[[58, 118], [50, 150]], [[70, 118], [64, 150]]] }) + arrow('M100 120 L124 128') + tag(120, 172, 'rock back till the forearm bites', 'middle'); },
    hipCircle: function () { return P.stand() + '<ellipse cx="120" cy="96" rx="30" ry="12" fill="none" stroke="' + ACC + '" stroke-width="2.4" stroke-dasharray="4 5"/>' + tag(120, 176, 'hands on hips — big slow circles', 'middle'); },
    ninety: function () { return ground(154, 20, 226) + fig({ h: [120, 44], n: [120, 58], s: [120, 66], hp: [120, 116], L: [[[80, 118], [80, 152]], [[160, 118], [160, 152]]], A: [[[126, 92], [130, 118]], [[114, 92], [110, 118]]] }) + arrow('M60 136 Q120 176 180 136') + tag(120, 30, 'knees sweep — both hips stay down', 'middle'); },
    band: function () { return ground(164) + shadow(120, 164, 28) + fig({ h: [120, 40], n: [120, 54], s: [120, 62], hp: [120, 104], L: [[[122, 136], [124, 163], [136, 163]], [[118, 136], [116, 163], [104, 163]]], A: [[[150, 30], [164, 14]], [[90, 30], [76, 14]]] }) + '<path d="M76 14 Q120 4 164 14" fill="none" stroke="' + ACC + '" stroke-width="3"/>' + arrow('M180 40 Q200 70 182 96') + tag(100, 176, 'wide grip, straight arms, over and behind', 'middle'); },
    couch: function () { return ground(164) + wall(200, 30, 164) + fig({ h: [120, 44], n: [120, 58], s: [120, 66], hp: [128, 112], L: [[[86, 130], [76, 163], [60, 163]], [[168, 138], [198, 100]]], A: [[[126, 92], [130, 114]], [[114, 92], [110, 114]]] }) + arrow('M150 90 L160 72') + tag(140, 66, 'glute ON, torso tall'); },
    hipFlexor: function () { return ground(164) + fig({ h: [120, 40], n: [120, 54], s: [120, 62], hp: [128, 108], L: [[[88, 126], [78, 163], [62, 163]], [[168, 136], [204, 163]]], A: [[[136, 36], [140, 10]], [[114, 88], [110, 108]]] }) + arrow('M172 120 L160 120') + tag(176, 110, 'rear glute on'); },
    frog: function () { return ground(154, 20, 226) + fig({ h: [40, 118], n: [56, 120], s: [62, 122], hp: [130, 128], L: [[[150, 152], [206, 148]], [[148, 104], [204, 108]]], A: [[[62, 150], [40, 150]], [[70, 150], [50, 150]]] }) + arrow('M130 100 L130 114') + tag(140, 104, 'hips sink back'); },
    pigeon: function () { return ground(154, 20, 226) + fig({ h: [48, 88], n: [62, 96], s: [68, 100], hp: [128, 132], L: [[[76, 152], [40, 146]], [[176, 140], [220, 150]]], A: [[[48, 122], [30, 150]], [[60, 126], [44, 152]]] }) + arrow('M120 100 L120 88') + tag(128, 94, 'hips square'); },
    wgs: function () { return ground(164) + fig({ h: [110, 40], n: [112, 54], s: [114, 62], hp: [112, 108], L: [[[156, 128], [154, 163], [172, 163]], [[80, 132], [50, 163]]], A: [[[128, 34], [136, 8]], [[94, 90], [90, 118]]] }) + arrow('M150 70 Q168 60 168 40') + tag(176, 52, 'rotate, reach'); },
    legsWall: function () { return ground(160, 20, 226) + wall(170, 20, 160) + fig({ h: [44, 148], n: [60, 146], s: [66, 144], hp: [140, 144], L: [[[160, 94], [166, 40]], [[158, 98], [164, 44]]], A: [[[80, 128], [104, 116]], [[84, 158], [110, 158]]] }) + tag(40, 60, 'hips a fist') + tag(40, 74, 'from the wall'); },
    lying: function () { return ground(154, 20, 226) + fig({ h: [40, 138], n: [56, 140], s: [62, 142], hp: [138, 144], L: [[[180, 146], [222, 148]], [[178, 144], [220, 146]]], A: [[[92, 152], [126, 154]], [[90, 130], [124, 130]]] }) + '<path d="M62 120 q8 -10 16 0 q8 10 16 0 q8 -10 16 0" fill="none" stroke="' + ACC + '" stroke-width="2.4"/>' + tag(150, 110, 'ten slow breaths', 'start'); },
    foamRoll: function () { return ground(154, 20, 226) + '<rect x="132" y="128" width="46" height="26" rx="13" fill="none" stroke="' + ACC + '" stroke-width="3"/>' + fig({ h: [48, 96], n: [62, 104], s: [68, 108], hp: [126, 120], L: [[[176, 118], [222, 128]], [[174, 122], [220, 132]]], A: [[[60, 138], [40, 154]], [[74, 140], [56, 154]]] }) + arrow('M190 110 L160 110') + tag(150, 100, 'slow passes; park on the tender spot'); },
    ballMassage: function () { return ground(154, 20, 226) + fig({ h: [46, 96], n: [60, 106], s: [66, 110], hp: [128, 120], L: [[[178, 118], [222, 128]], [[176, 122], [220, 132]]], A: [[[60, 138], [42, 154]], [[74, 140], [58, 154]]] }) + '<circle cx="110" cy="146" r="8" fill="' + ACC + '"/>' + tag(150, 100, 'ball under the tight spot — breathe'); },
    seated: function () { return ground(154, 20, 226) + fig({ h: [120, 44], n: [120, 58], s: [120, 66], hp: [120, 118], L: [[[80, 128], [88, 152]], [[160, 128], [152, 152]]], A: [[[132, 96], [140, 124]], [[108, 96], [100, 124]]] }) + arrow('M120 34 L120 18') + tag(128, 24, 'tall, soft eyes'); },
    palming: function () { return ground(154, 20, 226) + fig({ h: [120, 60], n: [120, 74], s: [120, 82], hp: [120, 126], L: [[[82, 134], [90, 154]], [[158, 134], [150, 154]]], A: [[[148, 90], [134, 58]], [[92, 90], [106, 58]]] }) + '<path d="M104 56 Q120 44 136 56" fill="none" stroke="' + ACC + '" stroke-width="3"/>' + tag(120, 30, 'warm palms, zero pressure, darkness', 'middle'); },
    eyeDrill: function () { return ground(164) + fig({ h: [60, 40], n: [60, 54], s: [60, 62], hp: [60, 106], L: [[[62, 136], [64, 163], [76, 163]], [[58, 136], [56, 163]]], A: [[[66, 86], [70, 108]], [[54, 86], [50, 108]]] }) + arrow('M78 40 L124 40') + arrow('M78 40 L170 60') + arrow('M78 40 L214 90') + tag(126, 34, 'near') + tag(172, 52, 'mid') + tag(216, 84, 'far'); },
    scan: function () { return P.seated() + '<rect x="24" y="12" width="192" height="130" rx="6" fill="none" stroke="' + ACC + '" stroke-width="1.6" stroke-dasharray="3 5"/>' + [[24, 12], [216, 12], [24, 142], [216, 142], [120, 12], [120, 142], [24, 77], [216, 77]].map(function (c) { return '<circle cx="' + c[0] + '" cy="' + c[1] + '" r="3.5" fill="' + ACC + '"/>'; }).join(''); },
    jaw: function () { return ground(164) + fig({ h: [120, 42], n: [120, 56], s: [120, 64], hp: [120, 106], L: [[[122, 136], [124, 163], [136, 163]], [[118, 136], [116, 163]]], A: [[[150, 70], [134, 52]], [[112, 88], [110, 108]]] }) + '<circle cx="128" cy="48" r="7" fill="none" stroke="' + ACC + '" stroke-width="2.4"/>' + tag(160, 40, 'jaw corner —') + tag(160, 54, 'slow circles'); },
    jawOpen: function () { return ground(164) + fig({ h: [120, 42], n: [120, 56], s: [120, 64], hp: [120, 106], L: [[[122, 136], [124, 163], [136, 163]], [[118, 136], [116, 163]]], A: [[[146, 80], [124, 58]], [[112, 88], [110, 108]]] }) + arrow('M120 66 L120 78') + tag(120, 176, 'open against the fist', 'middle'); },
    cheek: function () { return ground(164) + fig({ h: [120, 42], n: [120, 56], s: [120, 64], hp: [120, 106], L: [[[122, 136], [124, 163], [136, 163]], [[118, 136], [116, 163]]], A: [[[148, 72], [130, 44]], [[92, 72], [110, 44]]] }) + arrow('M150 48 L150 34') + arrow('M90 48 L90 34') + tag(120, 22, 'smile up, fingers resist', 'middle'); },
    scalp: function () { return ground(164) + fig({ h: [120, 44], n: [120, 58], s: [120, 66], hp: [120, 108], L: [[[122, 138], [124, 163], [136, 163]], [[118, 138], [116, 163]]], A: [[[150, 56], [136, 30]], [[90, 56], [104, 30]]] }) + '<path d="M104 28 a6 6 0 1 1 .1 0 M136 28 a6 6 0 1 1 .1 0" fill="none" stroke="' + ACC + '" stroke-width="2.2"/>' + tag(120, 176, 'fingertips, firm slow circles, whole scalp', 'middle'); },
    kegel: function () { return P.deepSquat() + '<path d="M40 40 q8 -10 16 0 q8 10 16 0" fill="none" stroke="' + ACC + '" stroke-width="2.4"/>' + tag(40, 60, 'breathe the floor') + tag(40, 74, 'open, then lift'); },
    coldShower: function () { return '<path d="M70 26 H150 M110 26 V44" stroke="' + INK + '" stroke-width="5" fill="none" stroke-linecap="round" opacity=".6"/>' + [82, 96, 110, 124, 138].map(function (x, i) { return '<path d="M' + x + ' 54 L' + (x - 3 + i) + ' 78 M' + (x + 6) + ' 90 L' + (x + 3 + i) + ' 112" stroke="' + ACC + '" stroke-width="2.4" stroke-linecap="round"/>'; }).join('') + '<text x="120" y="150" class="gd-t big" text-anchor="middle">30 s</text>' + tag(120, 172, 'exhale first, then turn the dial', 'middle'); },
    warmShower: function () { return '<path d="M70 26 H150 M110 26 V44" stroke="' + INK + '" stroke-width="5" fill="none" stroke-linecap="round" opacity=".6"/>' + [86, 104, 122, 140].map(function (x) { return '<path d="M' + x + ' 56 q6 12 0 24 q-6 12 0 24" fill="none" stroke="' + ACC + '" stroke-width="2.4" stroke-linecap="round"/>'; }).join('') + tag(120, 150, 'heat on the tight spots', 'middle'); },
    bed: function () { return '<path d="M30 118 V70 M210 118 V96 M30 96 H210 M30 118 H210" stroke="' + INK + '" stroke-width="5" fill="none" stroke-linecap="round" opacity=".6"/><rect x="38" y="80" width="40" height="16" rx="6" fill="' + INK + '" opacity=".35"/>' + tag(120, 46, 'dark · cool · quiet', 'middle') + '<circle cx="190" cy="40" r="8" fill="none" stroke="' + ACC + '" stroke-width="2.4"/><path d="M186 40 h8 M190 36 v8" stroke="' + ACC + '" stroke-width="2.4"/>'; },
    thermostat: function () { return '<circle cx="120" cy="86" r="46" fill="none" stroke="' + INK + '" stroke-width="4" opacity=".6"/><circle cx="120" cy="86" r="30" fill="none" stroke="' + ACC + '" stroke-width="2.2" stroke-dasharray="3 4"/><text x="120" y="94" class="gd-t big" text-anchor="middle">65–68°</text>' + tag(120, 156, 'blackout · silent', 'middle'); }
  };

  /* ---------- object drawings ---------- */
  var O = {
    bottle: function (label, cap) { return '<rect x="92" y="44" width="56" height="100" rx="12" fill="none" stroke="' + INK + '" stroke-width="4"/><rect x="104" y="26" width="32" height="20" rx="4" fill="' + INK + '" opacity=".7"/>' + (cap ? '<rect x="100" y="78" width="40" height="26" rx="4" fill="' + ACC + '" opacity=".35"/>' : '') + tag(120, 170, label, 'middle'); },
    tube: function (label) { return '<path d="M78 64 h84 l-6 78 h-72 z" fill="none" stroke="' + INK + '" stroke-width="4" stroke-linejoin="round"/><rect x="104" y="44" width="32" height="20" rx="3" fill="' + INK + '" opacity=".7"/>' + tag(120, 170, label, 'middle'); },
    pea: function () { return O.tube('one pea — whole face') + '<circle cx="190" cy="100" r="7" fill="' + ACC + '"/>' + tag(190, 124, 'this much', 'middle'); },
    fingers: function () { return '<path d="M78 40 V120 M108 40 V120" stroke="' + INK + '" stroke-width="18" stroke-linecap="round" fill="none"/><path d="M78 50 V110 M108 50 V110" stroke="' + ACC + '" stroke-width="6" stroke-linecap="round" opacity=".55"/>' + arrow('M132 84 L154 84') + '<ellipse cx="186" cy="84" rx="26" ry="32" fill="none" stroke="' + INK + '" stroke-width="4"/>' + tag(120, 170, 'two full finger-lengths', 'middle'); },
    face: function (label, dots) { return '<ellipse cx="120" cy="88" rx="44" ry="52" fill="none" stroke="' + INK + '" stroke-width="4"/>' + (dots ? [[100, 66], [140, 66], [120, 90], [102, 112], [138, 112]].map(function (c) { return '<path d="M' + c[0] + ' ' + c[1] + ' a8 8 0 1 1 .1 0" fill="none" stroke="' + ACC + '" stroke-width="2.4"/>'; }).join('') : '') + tag(120, 170, label, 'middle'); },
    stamp: function () { return '<ellipse cx="90" cy="96" rx="46" ry="54" fill="none" stroke="' + INK + '" stroke-width="4"/><path d="M60 78 q30 -16 60 0" fill="none" stroke="' + INK + '" stroke-width="3" opacity=".4"/><rect x="164" y="34" width="16" height="40" rx="3" fill="none" stroke="' + INK + '" stroke-width="4"/><line x1="160" y1="80" x2="184" y2="80" stroke="' + INK + '" stroke-width="5"/>' + arrow('M172 88 L172 106') + [[70, 66], [90, 60], [110, 66]].map(function (c) { return '<circle cx="' + c[0] + '" cy="' + c[1] + '" r="2.4" fill="' + ACC + '"/>'; }).join('') + tag(150, 130, 'tap · lift · move') + tag(150, 144, 'rows, no dragging'); },
    glass: function () { return '<path d="M84 34 H156 L146 150 H94 Z" fill="none" stroke="' + INK + '" stroke-width="4" stroke-linejoin="round"/><path d="M92 58 H148 L141 144 H99 Z" fill="' + ACC + '" opacity=".28"/>' + tag(120, 172, 'the whole thing, standing', 'middle'); },
    sun: function () { return '<circle cx="120" cy="80" r="26" fill="' + ACC + '" opacity=".9"/>' + [0, 45, 90, 135, 180, 225, 270, 315].map(function (a) { var r = a * Math.PI / 180; return '<line x1="' + (120 + Math.cos(r) * 36).toFixed(1) + '" y1="' + (80 + Math.sin(r) * 36).toFixed(1) + '" x2="' + (120 + Math.cos(r) * 48).toFixed(1) + '" y2="' + (80 + Math.sin(r) * 48).toFixed(1) + '" stroke="' + ACC + '" stroke-width="3" stroke-linecap="round"/>'; }).join('') + tag(120, 160, 'outside · no sunglasses · first hour', 'middle'); },
    journal: function (lines) { return '<rect x="56" y="30" width="128" height="110" rx="8" fill="none" stroke="' + INK + '" stroke-width="4"/><line x1="76" y1="30" x2="76" y2="140" stroke="' + INK + '" stroke-width="2" opacity=".35"/>' + (lines || [[92, 60, 160], [92, 82, 172], [92, 104, 148]]).map(function (l) { return '<line x1="' + l[0] + '" y1="' + l[1] + '" x2="' + l[2] + '" y2="' + l[1] + '" stroke="' + ACC + '" stroke-width="3" stroke-linecap="round"/>'; }).join('') + tag(120, 168, 'pen beats phone', 'middle'); },
    book: function () { return '<path d="M40 40 Q80 28 120 44 Q160 28 200 40 V140 Q160 128 120 144 Q80 128 40 140 Z" fill="none" stroke="' + INK + '" stroke-width="4" stroke-linejoin="round"/><line x1="120" y1="44" x2="120" y2="144" stroke="' + INK + '" stroke-width="3" opacity=".5"/>' + [64, 80, 96].map(function (y) { return '<line x1="56" y1="' + y + '" x2="104" y2="' + (y - 6) + '" stroke="' + ACC + '" stroke-width="2.4" stroke-linecap="round"/><line x1="136" y1="' + (y - 6) + '" x2="184" y2="' + y + '" stroke="' + ACC + '" stroke-width="2.4" stroke-linecap="round"/>'; }).join('') + tag(120, 170, 'paper. any book.', 'middle'); },
    phone: function (label) { return '<rect x="92" y="28" width="56" height="104" rx="10" fill="none" stroke="' + INK + '" stroke-width="4"/><line x1="112" y1="118" x2="128" y2="118" stroke="' + INK + '" stroke-width="3"/><path d="M44 50 L196 110" stroke="' + ACC + '" stroke-width="4" stroke-linecap="round"/>' + arrow('M156 66 L210 66') + tag(120, 166, label || 'charges in another room', 'middle'); },
    lamp: function () { return '<path d="M96 80 L144 80 L134 32 L106 32 Z" fill="none" stroke="' + INK + '" stroke-width="4" stroke-linejoin="round"/><line x1="120" y1="80" x2="120" y2="130" stroke="' + INK + '" stroke-width="4"/><path d="M96 130 h48" stroke="' + INK + '" stroke-width="5" stroke-linecap="round"/><path d="M84 88 q36 30 72 0" fill="' + ACC + '" opacity=".22"/>' + tag(120, 166, 'overheads off · lamps on · night mode', 'middle'); },
    bright: function () { return '<circle cx="80" cy="60" r="22" fill="' + ACC + '"/><path d="M80 92 v12 M52 60 h-14 M108 60 h14 M60 40 l-10 -10 M100 40 l10 -10" stroke="' + ACC + '" stroke-width="4" stroke-linecap="round"/><path d="M144 44 H192 L186 140 H150 Z" fill="none" stroke="' + INK + '" stroke-width="4" stroke-linejoin="round"/><path d="M150 66 H186 L181 134 H155 Z" fill="' + ACC + '" opacity=".28"/>' + tag(120, 172, 'brightest light, then the full glass', 'middle'); },
    coffee: function () { return '<path d="M70 70 H150 V120 Q150 140 130 140 H90 Q70 140 70 120 Z" fill="none" stroke="' + INK + '" stroke-width="4"/><path d="M150 82 h16 a12 12 0 0 1 0 24 h-16" fill="none" stroke="' + INK + '" stroke-width="4"/><path d="M90 40 q6 10 0 20 M110 36 q6 10 0 20 M130 40 q6 10 0 20" fill="none" stroke="' + ACC + '" stroke-width="2.4" stroke-linecap="round"/>' + tag(120, 166, '60–90 min after waking', 'middle'); },
    kitchen: function () { return '<rect x="52" y="44" width="136" height="90" rx="8" fill="none" stroke="' + INK + '" stroke-width="4"/><path d="M52 74 H188" stroke="' + INK + '" stroke-width="3" opacity=".5"/><path d="M76 94 h34 M76 110 h24" stroke="' + INK + '" stroke-width="3" opacity=".4" stroke-linecap="round"/><path d="M60 36 L180 142" stroke="' + ACC + '" stroke-width="4" stroke-linecap="round"/>' + tag(120, 166, 'closed 2–3 h before bed', 'middle'); },
    clock: function () { return '<circle cx="120" cy="84" r="44" fill="none" stroke="' + INK + '" stroke-width="4"/><path d="M120 84 V54 M120 84 L140 96" stroke="' + INK + '" stroke-width="4" stroke-linecap="round"/><path d="M84 140 L156 30" stroke="' + ACC + '" stroke-width="4" stroke-linecap="round"/>' + arrow('M170 84 L206 84') + tag(120, 166, 'face to the wall — no negotiating', 'middle'); },
    laidOut: function () { return '<rect x="40" y="70" width="52" height="60" rx="8" fill="none" stroke="' + INK + '" stroke-width="4"/><path d="M104 130 V80 l16 -14 h20 l16 14 V130 Z" fill="none" stroke="' + INK + '" stroke-width="4" stroke-linejoin="round"/><path d="M170 60 H198 L194 130 H174 Z" fill="none" stroke="' + INK + '" stroke-width="4" stroke-linejoin="round"/><path d="M174 80 h20 l-2 46 h-16 z" fill="' + ACC + '" opacity=".28"/>' + tag(120, 160, 'clothes · bag · water', 'middle') + tag(120, 174, 'where you\u2019ll trip on them', 'middle'); },
    floss: function () { return '<path d="M60 60 V130 M100 60 V130 M140 60 V130 M180 60 V130" stroke="' + INK + '" stroke-width="14" stroke-linecap="round"/><path d="M40 92 C 70 72, 90 112, 120 92 S 170 72, 200 92" fill="none" stroke="' + ACC + '" stroke-width="3"/>' + tag(120, 166, 'C-shape, below the gumline', 'middle'); },
    brush: function () { return '<rect x="36" y="80" width="130" height="14" rx="7" fill="none" stroke="' + INK + '" stroke-width="4"/><rect x="166" y="70" width="40" height="34" rx="6" fill="' + INK + '" opacity=".7"/>' + [172, 180, 188, 196].map(function (x) { return '<line x1="' + x + '" y1="70" x2="' + x + '" y2="58" stroke="' + ACC + '" stroke-width="3" stroke-linecap="round"/>'; }).join('') + '<text x="120" y="140" class="gd-t big" text-anchor="middle">2:00</text>' + tag(120, 166, 'spit, don\u2019t rinse', 'middle'); },
    tongue: function () { return '<path d="M60 60 Q120 40 180 60 Q190 110 120 140 Q50 110 60 60 Z" fill="none" stroke="' + INK + '" stroke-width="4"/><path d="M80 110 H160" stroke="' + ACC + '" stroke-width="4" stroke-linecap="round"/>' + arrow('M120 106 L120 72') + tag(120, 166, 'back to front, rinse the tool', 'middle'); },
    delete: function () { return '<rect x="66" y="36" width="108" height="108" rx="24" fill="none" stroke="' + INK + '" stroke-width="4"/><path d="M96 66 L144 114 M144 66 L96 114" stroke="' + ACC + '" stroke-width="5" stroke-linecap="round"/>' + tag(120, 166, 'one app · one account · one drawer', 'middle'); },
    target: function () { return '<circle cx="120" cy="84" r="46" fill="none" stroke="' + INK + '" stroke-width="4"/><circle cx="120" cy="84" r="28" fill="none" stroke="' + INK + '" stroke-width="3" opacity=".6"/><circle cx="120" cy="84" r="9" fill="' + ACC + '"/>' + tag(120, 166, 'the one task that makes today a win', 'middle'); },
    desk: function () { return '<rect x="56" y="48" width="128" height="80" rx="6" fill="none" stroke="' + INK + '" stroke-width="4"/><rect x="72" y="62" width="96" height="52" rx="3" fill="' + ACC + '" opacity=".22"/><line x1="120" y1="128" x2="120" y2="146" stroke="' + INK + '" stroke-width="4"/><line x1="92" y1="146" x2="148" y2="146" stroke="' + INK + '" stroke-width="4" stroke-linecap="round"/>' + tag(120, 168, 'one document · phone in another room', 'middle'); },
    outside: function () { return '<path d="M20 150 Q120 110 220 150" fill="none" stroke="' + INK + '" stroke-width="4" opacity=".5"/><circle cx="176" cy="52" r="18" fill="' + ACC + '" opacity=".9"/><path d="M40 100 q20 -30 40 0 q20 -30 40 0" fill="none" stroke="' + INK + '" stroke-width="3" opacity=".35"/>' + fig({ h: [110, 96], n: [110, 106], s: [110, 111], hp: [110, 136], L: [[[112, 152], [113, 166]], [[108, 152], [107, 166]]], A: [[[114, 124], [116, 138]], [[106, 124], [104, 138]]], r: 7 }) + tag(120, 176, 'two minutes of sky', 'middle'); },
    mirror: function () { return '<rect x="76" y="24" width="88" height="120" rx="10" fill="none" stroke="' + INK + '" stroke-width="4"/>' + fig({ h: [120, 56], n: [120, 68], s: [120, 74], hp: [120, 110], L: [[[121, 130], [122, 144]], [[119, 130], [118, 144]]], A: [[[126, 94], [128, 112]], [[114, 94], [112, 112]]], r: 9 }) + tag(120, 166, 'eyes on your own eyes — out loud', 'middle'); },
    speak: function (label) { return fig({ h: [90, 60], n: [90, 74], s: [90, 82], hp: [90, 124], L: [[[92, 146], [94, 164]], [[88, 146], [86, 164]]], A: [[[96, 102], [100, 122]], [[84, 102], [80, 122]]] }) + '<path d="M110 54 q16 -8 20 6 M116 38 q26 -10 34 14 M122 22 q36 -12 48 22" fill="none" stroke="' + ACC + '" stroke-width="2.6" stroke-linecap="round"/>' + tag(120, 176, label, 'middle'); },
    ledger: function () { return O.journal([[92, 56, 136], [92, 76, 150], [92, 96, 128], [92, 116, 158]]).replace('pen beats phone', 'promised · delivered · no commentary'); },
    checkmark: function (label) { return '<circle cx="120" cy="84" r="44" fill="none" stroke="' + INK + '" stroke-width="4"/><path d="M96 86 L114 104 L148 66" fill="none" stroke="' + ACC + '" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/>' + tag(120, 166, label, 'middle'); },
    feet: function () { return ground(150, 20, 226) + [84, 148].map(function (x) { return '<ellipse cx="' + x + '" cy="104" rx="16" ry="30" fill="' + INK + '" opacity=".85"/>' + [[-12, -40, 4], [-4, -46, 4.5], [4, -46, 4], [11, -43, 3.5], [16, -38, 3]].map(function (t) { return '<circle cx="' + (x + t[0]) + '" cy="' + (104 + t[1]) + '" r="' + t[2] + '" fill="' + INK + '" opacity=".85"/>'; }).join(''); }).join('') + arrow('M120 30 L120 56') + tag(120, 172, 'feet on the floor before the snooze exists', 'middle'); },
    box: function () { return '<rect x="66" y="30" width="108" height="108" rx="10" fill="none" stroke="' + INK + '" stroke-width="4"/>' + arrow('M66 70 L66 48') + arrow('M108 30 L130 30') + arrow('M174 98 L174 120') + arrow('M132 138 L110 138') + tag(36, 88, 'in 4', 'middle') + tag(120, 20, 'hold 4', 'middle') + tag(206, 88, 'out 4', 'middle') + tag(120, 160, 'hold 4', 'middle'); },
    wave: function (a, b, label) { var w = 200 / (a + b); return '<path d="M20 110 Q' + (20 + a * w / 2) + ' 30 ' + (20 + a * w) + ' 110 Q' + (20 + a * w + b * w / 2) + ' 30 ' + (20 + a * w + b * w) + ' 110" fill="none" stroke="' + INK + '" stroke-width="4" stroke-linecap="round"/>' + tag(20 + a * w / 2, 22, 'in ' + a, 'middle') + tag(20 + a * w + b * w / 2, 22, 'out ' + b + (b > a ? ' — longer' : ''), 'middle') + tag(120, 160, label, 'middle'); }
  };

  /* ---------- reference links: institutional pages verified in v4, otherwise an honest video search ---------- */
  function yt(q) { return { url: 'https://www.youtube.com/results?search_query=' + encodeURIComponent(q), label: 'Watch it — ' + q, search: true }; }
  var CC = 'Cleveland Clinic', HL = 'Healthline';
  var L = {
    pushup: { url: 'https://health.clevelandclinic.org/how-to-do-a-push-up', label: 'Push-up form — ' + CC },
    squat: { url: 'https://www.healthline.com/health/fitness-exercise/proper-squat-form', label: 'Squat form — ' + HL },
    plank: { url: 'https://health.clevelandclinic.org/plank-exercise-benefits', label: 'Plank form — ' + CC },
    deadhang: { url: 'https://www.healthline.com/health/fitness-exercise/dead-hang', label: 'Dead hang — ' + HL },
    couch: { url: 'https://www.healthline.com/health/couch-stretch', label: 'Couch stretch — ' + HL },
    box: { url: 'https://health.clevelandclinic.org/box-breathing-benefits', label: 'Box breathing — ' + CC },
    belly: { url: 'https://my.clevelandclinic.org/health/articles/9445-diaphragmatic-breathing', label: 'Belly breathing — ' + CC },
    spf: { url: 'https://www.aad.org/public/everyday-care/sun-protection/shade-clothing-sunscreen/how-to-apply-sunscreen', label: 'How to apply sunscreen — AAD' },
    legswall: { url: 'https://health.clevelandclinic.org/benefits-of-legs-up-the-wall', label: 'Legs up the wall — ' + CC },
    cold: { url: 'https://health.clevelandclinic.org/are-cold-showers-good-for-you', label: 'Cold showers — ' + CC }
  };

  /* ---------- the guides ----------
     order matters: the first regex that matches wins, so specific entries sit above general ones. */
  function g(id, rx, t, how, miss, link, draw, cat) { return { id: id, rx: rx, t: t, how: how, miss: miss, link: link, draw: draw, cat: cat || 'body' }; }
  G.GUIDES = [
    /* ---- gates + strength ---- */
    g('pike', /pike/i, 'Pike push-up — the shoulder press without a bar',
      ['Downward-dog shape: hips high, hands shoulder-width, heels light', 'Bend the elbows and lower the crown of the head toward the floor between the hands', 'Press back up until the arms lock', 'Keep the hips over the hands the whole way — you press up, not forward'],
      'Letting the hips drift forward turns it into a bad push-up', yt('pike push up form'), P.pike),
    g('pushup', /push.?up|第一|shurad\u014d \u2014 the machine|拳/i, 'Push-up — the honest rep',
      ['Hands under the shoulders, body one straight line from crown to heels', 'Lower until the chest is a fist from the floor, elbows about 45° from the ribs', 'Push the floor away; lock out and squeeze the glutes at the top', '\u201cForm failure\u201d means the hips sag or the neck cranes — stop one rep before it'],
      'Hips sagging or piking up — the rep counts only if the line holds', L.pushup, P.pushupFail),
    g('deepsquat', /deep squat|squat hold|chikush\u014dd\u014d \u2014 the summons|reverse kegels \u2014 deep/i, 'Deep squat hold — live in the bottom',
      ['Sink all the way down, heels flat; hold something if the heels lift', 'Elbows inside the knees, pry them gently out, chest proud', 'Breathe into the belly — every exhale sinks a little further', 'Stay. The hold does the work, not the depth'],
      'Rounding the back to get lower — height in the chest beats depth in the hips', yt('deep squat hold mobility'), P.deepSquat),
    g('squat', /squat|第二|脚|chikush\u014dd\u014d \u2014 the count/i, 'Squat — sit between the heels',
      ['Feet shoulder-width, toes slightly out, weight in the whole foot', 'Hips back, then down; chest proud, eyes ahead', 'Knees track over the toes; heels never leave the floor', 'Below parallel if the heels allow. Drive up through the mid-foot'],
      'Knees caving inward or heels lifting — shorten the depth before you let either happen', L.squat, P.squat),
    g('wallsit', /wall sit|第七/i, 'Wall sit — the chair that isn\u2019t there',
      ['Back flat on the wall, feet out in front, shoulder-width', 'Slide down until the thighs are level with the floor — knees over ankles', 'Hands off the thighs. Shoulders relaxed, breathing steady', 'When it burns, breathe slower, not faster'],
      'Thighs above parallel or hands on the legs — both make it a rest, not a hold', yt('wall sit form'), P.wallsit),
    g('revlunge', /reverse lunge/i, 'Reverse lunge — step back, stay tall',
      ['Stand tall; step one foot back onto the ball of the foot', 'Lower straight down until the back knee kisses the floor', 'Front shin stays vertical, chest up, ribs stacked over hips', 'Drive through the front heel to stand; alternate sides'],
      'Leaning the torso forward — think elevator, not escalator', yt('reverse lunge form'), P.revLunge),
    g('lunge', /lunge|第三/i, 'Lunge — the knee kisses the floor',
      ['Step long enough that both knees make right angles at the bottom', 'Lower straight down; the back knee taps the floor lightly', 'Front knee over the ankle, not past the toes; torso upright', 'Push through the front heel to return; alternate'],
      'A short step that shoves the front knee past the toes — step longer', yt('forward lunge form'), P.lunge),
    g('sideplank', /side plank|plank of the ancestors/i, 'Side plank — one line, hips high',
      ['Elbow under the shoulder, feet stacked or staggered', 'Lift the hips until ear, shoulder, hip and ankle line up', 'Top hand on the hip or reaching up; look straight ahead', 'The chime flips you — same count both sides'],
      'Hips drifting toward the floor — if you can\u2019t lift them, drop to the knees and keep the line', yt('side plank form'), P.sidePlank),
    g('plank', /plank|第四|shurad\u014d \u2014 the frame/i, 'Plank — the frame holds',
      ['Elbows under the shoulders, forearms flat, fists soft', 'Squeeze the glutes and pull the ribs down — one line, no sag, no tent', 'Breathe small and steady; the shape does not move', 'Shaking is fine. Sagging is the end of the set'],
      'Hips sinking as fatigue sets in — reset the glutes or end the set', L.plank, P.plank),
    g('hollow', /hollow|第八|core gauntlet|芯/i, 'Hollow hold — low back welded down',
      ['Lie on the back; press the whole lower back into the floor and keep it there', 'Lift the shoulders and straight legs a few inches — arms reaching past the ears', 'The lower the legs, the harder. If the back lifts, raise the legs', 'Breathe. The shape is small and shaking'],
      'The lower back arching off the floor — that\u2019s the entire exercise gone', yt('hollow body hold form'), P.hollow),
    g('deadbug', /dead bug/i, 'Dead bug — opposite arm and leg, back pinned',
      ['On the back, arms straight up, knees over the hips at 90°', 'Press the low back into the floor — it stays there for every rep', 'Lower one arm overhead and the opposite leg toward the floor, slow', 'Return, switch. If the back arches, the rep didn\u2019t count'],
      'Rushing — the slowness is what makes the core work', yt('dead bug exercise form'), P.deadbug),
    g('superman', /superman/i, 'Superman hold — chest and thighs off the floor',
      ['Face down, arms long past the head, legs straight', 'Lift the chest and the thighs together — squeeze glutes and mid-back', 'Eyes down; the neck stays long, not cranked up', 'Hold and breathe; lower slow'],
      'Looking up — it strains the neck and steals from the back muscles', yt('superman hold exercise'), P.superman),
    g('bridge', /glute bridge/i, 'Glute bridge — wake the engine',
      ['On the back, knees bent, heels close to the hips', 'Drive through the heels; lift the hips until the body is a line from knees to shoulders', 'Squeeze the glutes hard for two seconds at the top; ribs down', 'Lower with control; don\u2019t bounce off the floor'],
      'Arching the low back to go higher — the height comes from the glutes', yt('glute bridge form'), P.bridge),
    g('mtnclimber', /mountain climber|第六/i, 'Mountain climbers — fast feet, hips low',
      ['Plank on the hands, shoulders stacked over the wrists', 'Drive one knee toward the chest, then switch — feet light and quick', 'Hips stay low and level; the torso does not bounce', 'Breathe rhythmically; the pace is yours, the shape isn\u2019t'],
      'Hips rising into a pike as speed goes up — slow down and keep the plank', yt('mountain climbers form'), P.mtnClimber),
    g('burpee', /burpee|第五/i, 'Burpee — full chest, full jump',
      ['Squat, hands to the floor, kick the feet back into a plank', 'Lower the chest all the way to the floor', 'Push up, snap the feet back under you', 'Stand and jump — hands over the head, land soft'],
      'Skipping the chest-to-floor or the jump — a half burpee pays half', yt('burpee form'), P.burpee),
    g('deadhang', /dead hang|^hang/i, 'Dead hang — let the spine open',
      ['Full grip, arms straight, shoulders relaxed and pulled up around the ears', 'Let the ribs drop away from the bar; feet off the floor, still', 'Nasal breathing into the stretch — no swinging', 'It ends when the grip ends, not when the mood does'],
      'Shrugging the shoulders down actively — the hang is passive, let gravity work', L.deadhang, P.deadhang),
    g('calfraise', /calf raise/i, 'Calf raises — slow up, slower down',
      ['Stand tall, balls of the feet on the floor (or an edge for range)', 'Rise as high as possible onto the toes — pause at the top', 'Lower for three full seconds, heels sinking below the toes if on an edge', 'No bouncing at the bottom'],
      'Bouncing — it hands the work to the tendon instead of the muscle', yt('calf raise form'), P.calfRaise),
    /* ---- warm-up + motion ---- */
    g('gatestance', /gate stance/i, 'Gate stance — announce the work',
      ['Feet shoulder-width, rooted; fists at the ribs', 'One long breath in through the nose, chest wide', 'Exhale slowly, shoulders down, eyes ahead', 'Say the first movement out loud. Then begin'],
      'Rushing into the first set — twenty seconds of stillness sets the tone', yt('rock lee eight gates stance'), P.standArrow),
    g('jumpingjack', /jumping jack/i, 'Jumping jacks — light and springy',
      ['Feet together, arms at the sides, knees soft', 'Jump the feet wide as the arms rise overhead', 'Jump back together as the arms come down', 'Land quiet on the balls of the feet; steady rhythm'],
      'Heavy flat-footed landings — think spring, not stomp', yt('jumping jacks form'), P.jumpingJack),
    g('armcircle', /arm circle/i, 'Arm circles — small to large',
      ['Arms straight out to the sides at shoulder height', 'Small circles forward, growing larger every few reps', 'Reverse: small backward, growing larger', 'Shoulders stay down away from the ears'],
      'Shrugging up as the circles grow — keep the neck long', yt('arm circles warm up'), P.armCircles),
    g('legswing', /leg swing/i, 'Leg swings — grease the hip',
      ['One hand on the wall, stand tall on one leg', 'Swing the other leg front-to-back, growing the range each rep, torso still', 'Then side-to-side across the body', 'Both legs, same count; controlled, not flung'],
      'Twisting the torso to swing higher — the hip moves, the spine does not', yt('leg swings warm up'), P.legSwing),
    g('sprint', /sprint/i, 'Sprint — all out, short',
      ['Tall posture, slight forward lean from the ankles', 'Drive the knees, pump the arms — elbows about 90°', 'Land under the hips on the ball of the foot', 'All out for the whole interval; slow the last two steps, don\u2019t stop dead'],
      'Overstriding — landing with the foot way out front is a brake', yt('sprint form drills'), P.sprint),
    g('walkback', /walk back/i, 'Walk back — nose breathing',
      ['Walk, don\u2019t stand. Hands off the knees', 'Breathe in and out through the nose only', 'Shake the arms loose, shoulders down', 'Arrive at the line ready, not gasping'],
      'Bending over with hands on knees — stay tall and let the lungs open', yt('active recovery between sprints'), P.walk),
    g('askip', /a-skip/i, 'A-skips — tall, knees driving',
      ['Skip with one knee driving up to hip height, opposite arm forward', 'Foot snaps down under the hip; quick ground contact', 'Stay tall — crown of the head leads', 'Rhythm over speed; it\u2019s a drill, not a race'],
      'Leaning back — keep the chest over the hips', yt('a skip drill form'), P.aSkip),
    g('pogo', /pogo/i, 'Pogo hops — stiff ankles, quiet feet',
      ['Feet together, knees nearly straight, arms relaxed', 'Bounce off the balls of the feet — the ankle is the spring', 'Minimal ground contact, quiet landings', 'Small hops; height is not the point, stiffness is'],
      'Bending the knees to get height — this trains the ankle, keep the knees quiet', yt('pogo hops drill'), P.pogo),
    g('run', /\u8d70|the run$/i, 'The run — out the door',
      ['Easy pace first five minutes, then whatever the day is', 'Tall, relaxed shoulders, quick light steps', 'Breathe through the nose as long as you can', 'Log the miles when you\u2019re back — the number lives on the day'],
      'Starting too fast — the first mile sets the tone, make it easy', yt('proper running form beginners'), P.sprint),
    g('shake', /shake/i, 'Shake down — loose limbs, tall spine',
      ['Stand tall; let the arms hang heavy', 'Shake the hands and forearms, then the shoulders, then each leg', 'Bounce lightly through the knees; jaw loose', 'Finish still, with one long exhale'],
      'Skipping it — this is how the body learns the set is over', yt('shake out warm up cool down'), P.shake),
    g('overhead', /overhead reach|youth stretch/i, 'Overhead reach — ribs tall, long exhale',
      ['Fingers laced, palms turned to the ceiling', 'Reach up; keep the ribs down, not flared', 'Exhale long as you reach; lengthen the sides of the body', 'Lean gently to each side if it feels good'],
      'Arching the lower back to reach higher — reach from the ribs', yt('standing overhead reach stretch'), P.overheadReach),
    g('fists', /fists to the sky/i, 'Fists to the sky — ten slow punches',
      ['Stand tall, feet rooted', 'Punch straight up, one arm at a time, slow and full', 'Exhale on every punch; eyes up', 'Full intent. This is the last thing the body does before the day'],
      'Fast, lazy reps — slow is the point', yt('standing overhead punches warm up'), P.fists),
    g('stand', /^stand |^stand$|taller than|water and posture|rise on the first/i, 'The stance — taller than yesterday',
      ['Feet rooted, weight even across both feet', 'Ribs stacked over hips, crown of the head reaching up', 'Shoulders back and down — proud, not puffed', 'Hold it for one slow breath before you move'],
      'Chest thrust forward with the ribs flared — stack, don\u2019t puff', yt('good standing posture'), P.standArrow),
    /* ---- neck, shoulders, spine ---- */
    g('doorway', /doorway/i, 'Doorway pec stretch — step through',
      ['Forearms on the door frame, elbows just below shoulder height', 'Step one foot through until the chest opens', 'Ribs down, chin tucked — stretch the chest, not the low back', 'Hold and breathe; ease off, never bounce'],
      'Leaning forward from the hips — the step is small, the chest does the opening', yt('doorway pec stretch'), P.doorway),
    g('chintuck', /chin tuck/i, 'Chin tucks — a double chin, not a nod',
      ['Sit or stand tall, eyes level', 'Glide the chin straight back as if making a double chin', 'Hold two seconds; feel the back of the neck lengthen', 'Release slowly. Five reps, never fast'],
      'Nodding down instead of gliding back — the eyes stay level', yt('chin tuck exercise'), P.chinTuck),
    g('wallangel', /wall angel/i, 'Wall angels — slide, stay on the wall',
      ['Back, head and hips against the wall; feet a few inches out', 'Arms in a goalpost against the wall, ribs down', 'Slide the arms up as far as they stay on the wall', 'Slide down; ten slow reps'],
      'Arching the low back to keep the arms on the wall — shrink the range instead', yt('wall angels exercise'), P.wallAngel),
    g('neckroll', /neck roll/i, 'Neck rolls — the front half only',
      ['Sit tall; drop the chin toward the chest', 'Roll the ear toward one shoulder, then back across the chest to the other', 'Slow half-circles — never around the back', 'Breathe; let the weight of the head do it'],
      'Circling through the back — it grinds the joints; the half-circle is the whole drill', yt('neck rolls stretch safe'), P.neckRoll),
    g('neckiso', /neck iso|iron neck|4-way neck/i, 'Neck isometrics — push, and the neck refuses',
      ['Sit tall. Palm on the forehead; push the head into the palm, the palm pushes back', 'Nothing moves — hold five seconds, release', 'Back of the head, then each side, same law', 'Three pushes per direction; gentle, then firm'],
      'Letting the head actually move — this is a hold, not a stretch', yt('neck isometric exercises'), P.neckIso),
    g('catcow', /cat.?cow/i, 'Cat–cow — the breath drives the spine',
      ['Hands under shoulders, knees under hips', 'Inhale: belly drops, chest lifts, gaze forward (cow)', 'Exhale: round the spine up, chin to chest (cat)', 'Slow — one full breath per shape'],
      'Rushing the shapes — the breath sets the pace, not the spine', yt('cat cow stretch'), P.catcow),
    g('wristrock', /wrist rock/i, 'Kneeling wrist rocks — rock till the forearm bites',
      ['Kneel; palms flat, fingers pointing back toward the knees', 'Rock the hips back gently until the forearms bite', 'Rock forward, release; repeat', 'Then flip: backs of the hands down, fingers forward'],
      'Forcing it — the wrist opens slowly over weeks', yt('wrist mobility kneeling rocks'), P.wristRock),
    g('hipcircle', /hip circle/i, 'Standing hip circles — grease, don\u2019t stretch',
      ['Feet wide, hands on the hips', 'Big slow circles with the hips, one direction', 'Then the other; the head stays roughly still', 'Loose and easy — this is a warm-up, not a stretch'],
      'Small, tight circles — make them big', yt('standing hip circles warm up'), P.hipCircle),
    g('ninety', /90\/90/i, '90/90 hip switches — both hips stay down',
      ['Sit with both knees bent at 90°, one leg forward, one to the side', 'Chest tall; sweep both knees to the other side', 'Both hips try to stay on the floor the whole way', 'Slow switches; pause at each end'],
      'Leaning back on the hands to make it easy — chest tall, hands light', yt('90 90 hip switches'), P.ninety),
    g('band', /dislocate/i, 'Banded dislocates — widen the grip first',
      ['Hold a band wide, arms straight, in front of the hips', 'Bring the band up and over the head to behind the back — arms stay straight', 'Return the same way', 'Too hard? Widen the grip. Never bend the elbows to make it'],
      'Bending the elbows mid-arc — that\u2019s the shoulder cheating', yt('banded shoulder dislocates'), P.band),
    /* ---- hips, legs, floor ---- */
    g('couch', /couch stretch/i, 'Couch stretch — glute on, torso tall',
      ['Kneel with one shin up the wall, that knee in the corner', 'Other foot forward, flat', 'Squeeze the back glute and lift the torso tall — the stretch arrives on its own', 'Breathe. The chime flips your side'],
      'Arching the lower back to feel more — squeeze the glute instead', L.couch, P.couch),
    g('hipflexor', /hip flexor/i, 'Half-kneeling hip flexor stretch — the stand-taller one',
      ['Half-kneel; back knee on the floor, front foot flat', 'Squeeze the back glute — the pelvis tucks under', 'Reach the same-side arm tall and slightly across', 'Hold, breathe; switch'],
      'Leaning forward into the front leg — the stretch comes from the glute squeeze', yt('half kneeling hip flexor stretch'), P.hipFlexor),
    g('frog', /frog stretch/i, 'Frog stretch — hips sink back',
      ['Knees wide, feet turned out, forearms on the floor', 'Sink the hips back toward the heels', 'Exhale into it; hold at the first honest edge', 'Never bounce; ninety seconds is a long time'],
      'Going too wide too fast — inch the knees out over weeks', yt('frog stretch adductors'), P.frog),
    g('pigeon', /pigeon/i, 'Pigeon pose — hips square, chest melts',
      ['One shin forward on the floor, the other leg long behind', 'Square the hips — keep the back leg straight, not rolled open', 'Chest lifts, then melts forward over the shin', 'Breathe; the chime flips your side'],
      'Rolling onto the hip of the front leg — keep the hips square even if you stay higher', yt('pigeon pose hips'), P.pigeon),
    g('wgs', /world.?s greatest/i, 'World\u2019s greatest stretch — flow, don\u2019t hold',
      ['Long lunge; both hands inside the front foot', 'Elbow drops toward the instep', 'Rotate — that hand reaches to the sky, eyes follow', 'Return, switch sides; keep moving'],
      'Holding each shape — this one flows', yt('worlds greatest stretch'), P.wgs),
    g('foamroll', /foam roll/i, 'Foam rolling — slow passes, park on the tender spot',
      ['Roller under the muscle; body weight on it, not on the hands', 'Slow passes — an inch per second', 'Find a tender spot, stop there, breathe for a few seconds', 'Quads, glutes, calves. Never the joint itself'],
      'Rolling fast back and forth — it does nothing; slow is the medicine', yt('foam rolling legs technique'), P.foamRoll),
    g('selfmassage', /self-massage|assess the vessel|damage report/i, 'Self-massage — the ball goes where today landed',
      ['Thirty seconds first: what is tight, what hurts', 'Ball or hands on that spot; slow pressure, breathe', 'Hold until it softens — then move an inch', 'Slow beats hard'],
      'Chasing pain — if it makes you brace, ease off', yt('lacrosse ball self massage'), P.ballMassage),
    g('legswall', /legs up the wall/i, 'Legs up the wall — the drain',
      ['Hips a fist from the wall, legs straight up', 'Arms open, palms up, jaw loose', 'Stay three to five minutes; gravity does the work', 'This is the off switch. Do nothing well'],
      'Fidgeting — the stillness is the point', L.legswall, P.legsWall),
    g('groundcontact', /ground contact|body scan|stillness rule|bed is for sleep/i, 'Ground contact — feel every touchpoint',
      ['Lie flat; feel the heels, calves, back, shoulders, head', 'Ten slow breaths; let each station unclench', 'Feet to crown, one region at a time', 'If sleep comes, let it'],
      'Counting or checking the time — that\u2019s the mind at work; you\u2019re here to rest it', yt('body scan meditation'), P.lying),
    g('kegel', /kegel/i, 'Kegels + reverse — squeeze and lift, then release',
      ['Squeeze as if stopping a stream and lift upward; hold three seconds', 'Release fully — the release is half the rep', 'Then reverse: belly-breathe and let the floor drop and open', 'Breathe through all of it; nothing else tenses'],
      'Holding the breath or squeezing the glutes — isolate the floor', yt('kegel and reverse kegel'), P.kegel),
    /* ---- eyes, face, mind ---- */
    g('seated', /^sit —|see everything|the seat$/i, 'Sit — arrive before anything begins',
      ['Sit tall, hands empty, feet flat', 'Eyes soft; notice the whole room without turning the head', 'Breathe slow. Nothing to do yet', 'Then write or begin — from stillness, not from the rush'],
      'Sitting with the phone in reach — nothing in the hands', yt('one minute sitting meditation'), P.seated),
    g('eyedrill', /20\/20\/20/i, '20/20/20 — near, mid, far',
      ['Twenty seconds focusing on something close — a hand', 'Twenty seconds on something mid-room', 'Twenty seconds on something far, ideally out a window', 'Blink fully between each; let the eyes rest on the far point'],
      'Straining to see the far point — soft eyes, let them settle', yt('20 20 20 eye exercise'), P.eyeDrill),
    g('palming', /palming/i, 'Palming — darkness for the eyes',
      ['Rub the palms warm', 'Cup them over closed eyes — zero pressure on the eyeballs', 'Total darkness; breathe slow for the whole minute', 'Lift the hands, open the eyes gently'],
      'Pressing on the eyes — the palms hover, they don\u2019t press', yt('palming eyes relaxation'), P.palming),
    g('eightscan', /eight-point/i, 'Eight-point scan — eyes only, head still',
      ['Head still, chin level', 'Trace the room\u2019s corners with the eyes only: top-left, top, top-right, right…', 'Full circuit slowly; then reverse', 'Blink when you need to'],
      'Turning the head — the whole drill is the eyes moving alone', yt('eye movement exercises corners'), P.scan),
    g('scalp', /scalp massage/i, 'Scalp massage — four minutes, firm slow circles',
      ['Fingertips (never nails) on the scalp', 'Firm, slow circles — move the skin over the skull', 'Cover the whole scalp: front, crown, sides, back', 'Gentle over the itchy zones'],
      'Rubbing the hair instead of moving the scalp — press until the skin moves', yt('standardized scalp massage'), P.scalp),
    g('jaw', /masseter/i, 'Masseter release + rest posture',
      ['Knuckles on the jaw corners; slow circles, moderate pressure', 'Let the jaw hang; breathe', 'Finish in rest posture: tongue on the palate, lips closed, teeth apart', 'Nasal breathing. That posture is the default from now on'],
      'Clenching to \u201cfeel\u201d the muscle — the jaw stays slack while you work it', yt('masseter release massage'), P.jaw),
    g('cheek', /cheek lifter/i, 'Cheek lifters — smile the cheeks up',
      ['Fingers rest lightly on the cheekbones', 'Smile the cheeks upward against the light resistance', 'Hold five seconds; release', 'Ten reps; eyes relaxed'],
      'Squinting or tensing the forehead — only the cheeks move', yt('cheek lifter face exercise'), P.cheek),
    g('jawopen', /resisted jaw/i, 'Resisted jaw openings — open against the fist',
      ['Fist under the chin', 'Open the mouth slowly against it — five seconds', 'Close slowly; the fist keeps resisting', 'Ten reps; never to pain'],
      'Pushing the fist up so hard the jaw can\u2019t open — resistance, not a lock', yt('resisted jaw opening exercise'), P.jawOpen),
    g('boxbreath', /box breath|tend\u014d/i, 'Box breathing — four equal walls',
      ['In through the nose — four', 'Hold, shoulders down — four', 'Out slow through the mouth — four', 'Hold empty — four. That is one lap'],
      'Forcing the holds — if four is too long, do three; equal sides matter more', L.box, O.box, 'mind'),
    g('breath478', /4-?7-?8|ged\u014d/i, '4-7-8 — the long exhale ends the day',
      ['In through the nose for four', 'Hold for seven', 'Out through the mouth for eight, slow and audible', 'Four cycles. Jaw loose, shoulders heavy'],
      'Gasping the inhale — it\u2019s quiet and low, the exhale is the work', L.belly, function () { return O.wave(4, 8, 'in 4 · hold 7 · out 8'); }, 'mind'),
    g('bellybreath', /belly breath|slow belly/i, 'Belly breathing — only the hand rises',
      ['Hand on the stomach', 'Inhale low — only that hand should rise, four counts', 'Exhale long — six counts', 'Ten rounds; slower each time'],
      'Breathing into the chest — if the shoulders rise, start again lower', L.belly, function () { return O.wave(4, 6, 'the hand on the belly rises'); }, 'mind'),
    g('breath', /breath/i, 'Slow breathing — the exhale is the jutsu',
      ['Nose in, low into the belly', 'The exhale runs longer than the inhale', 'Jaw loose, shoulders heavy', 'Count the pattern; the count is the anchor'],
      'Racing the count — slower, always', L.belly, function () { return O.wave(4, 6, 'in, then out — longer'); }, 'mind'),
    /* ---- skin ---- */
    g('cleanse', /^cleanse|face cleanser/i, 'Cleanse — thirty seconds, fingertips',
      ['Lukewarm water; a coin of cleanser in wet hands', 'Small circles with the fingertips — every zone, thirty full seconds', 'Rinse completely, especially the hairline and jaw', 'Pat dry. Never drag the towel'],
      'Hot water and scrubbing — stripping oily skin makes it oilier', yt('how to wash your face dermatologist'), function () { return O.face('small circles, every zone', true); }, 'skin'),
    g('bpwash', /panoxyl|bp shower|acne wash|^shower —/i, 'BP wash — the dwell is the medicine',
      ['Lather the 4% onto wet face, chest, shoulders, back', 'Let it sit 60–90 seconds while you do your hair', 'Rinse thoroughly', 'White towel only — benzoyl peroxide bleaches'],
      'Rinsing immediately — without the dwell it barely works', yt('benzoyl peroxide wash how to use'), function () { return O.bottle('sit 60–90 s · white towel', true); }, 'skin'),
    g('adapalene', /adapalene|retinoid|differin/i, 'Adapalene — one pea, bone-dry face',
      ['Wait 10–15 minutes after washing — the face must be fully dry', 'One pea-sized amount for the whole face; dot and spread thin', 'Avoid the eyes, nostril creases and lips', 'First two weeks: three nights on. Then nightly. The purge (weeks 2–6) is normal — do not quit'],
      'Using it as a spot treatment or on damp skin — thin, everywhere, dry', yt('how to apply adapalene differin'), O.pea, 'skin'),
    g('moisturize', /moistur/i, 'Moisturize — right over it',
      ['Quarter-size amount', 'Press and spread over the whole face and neck', 'Straight on top of the adapalene — it buffers, it doesn\u2019t cancel', 'Don\u2019t skip it on oily nights; barrier first'],
      'Skipping it because the skin feels oily — a broken barrier makes more oil', yt('how to apply moisturizer face'), function () { return O.tube('quarter-size · face + neck'); }, 'skin'),
    g('lipspf', /^lip/i, 'Lip SPF — one pass',
      ['One full pass over both lips', 'Include the border where the lip meets skin', 'Reapply after eating or drinking', 'Lips burn first and lie about it'],
      'Forgetting it because the face is done — lips are skin too', L.spf, function () { return O.tube('one pass, including the border'); }, 'skin'),
    g('spf', /spf|sunscreen/i, 'Sunscreen — the two-finger law',
      ['Squeeze two full finger-lengths for face and neck', 'It will feel like too much. That is the correct amount', 'Ears, hairline, jaw, the back of the neck', 'Reapply if the sun outlasts you'],
      'A pea-sized smear — under-applying is the most common sunscreen failure', L.spf, O.fingers, 'skin'),
    /* ---- hair ---- */
    g('keto', /keto|nizoral/i, 'Ketoconazole — five full minutes on the scalp',
      ['Wet hair; lather into the scalp, not the lengths', 'Let it sit five full minutes — the timer is the medicine', 'Rinse; condition the lengths', 'Twice a week, spaced apart'],
      'Rinsing after thirty seconds — the dwell is the entire treatment', yt('ketoconazole shampoo how to use'), function () { return O.bottle('5:00 on the scalp', true); }, 'hair'),
    g('gentlewash', /wash night|gentle shampoo/i, 'Wash night — scalp only, condition the ends',
      ['Gentle shampoo on the scalp only; fingertips, not nails', 'Let the suds run through the lengths on the rinse — that\u2019s enough', 'Conditioner from mid-length to ends, never the roots', 'Three washes a week keeps the oil the curls need'],
      'Shampooing the lengths — it strips them; the scalp is the target', yt('how to wash curly hair'), function () { return O.bottle('scalp only · condition the ends'); }, 'hair'),
    g('minoxidil', /minoxidil|rogaine/i, 'Minoxidil — half cap, dry scalp',
      ['Scalp fully dry', 'Half a cap of foam; part the hair into rows', 'Massage into the thinning zones, not the hair', 'Wash the hands. Every night except stamp night'],
      'Applying to a damp scalp — it dilutes and runs; dry means dry', yt('how to apply minoxidil foam'), function () { return O.bottle('half cap · DRY scalp · rows'); }, 'hair'),
    g('stamp', /derma|stamp night|derma stamp/i, 'Derma stamp — the marked ground',
      ['Clean scalp, clean stamp — always', 'Light vertical taps; lift and move. No dragging, no pressure', 'Work the thinning zones in rows; each spot once', 'Nothing on the scalp tonight — minoxidil resumes tomorrow'],
      'Dragging or pressing hard — bleeding is not the goal, the taps are', yt('derma stamp scalp technique'), O.stamp, 'hair'),
    /* ---- oral ---- */
    g('floss', /floss/i, 'Floss first — the C-shape',
      ['Before the brush, not after', 'Slide between the teeth; curve into a C around one tooth', 'Below the gumline, gently up and down', 'Both sides of every gap'],
      'Snapping it straight down into the gum — curve and slide', yt('how to floss properly'), O.floss, 'oral'),
    g('brush', /brush/i, 'Brush — two full minutes',
      ['Soft bristles at 45° to the gumline', 'Small circles; thirty seconds per quarter of the mouth', 'Inner surfaces, chewing surfaces, then the tongue', 'Spit, don\u2019t rinse — the fluoride keeps working'],
      'Rinsing with water at the end — it washes off the medicine', yt('how to brush teeth properly'), O.brush, 'oral'),
    g('tongue', /tongue/i, 'Tongue scrape — back to front',
      ['Reach as far back as is comfortable', 'One firm pass forward', 'Rinse the tool; repeat three or four times', 'Rinse the mouth'],
      'Scraping the tip only — the coating lives at the back', yt('tongue scraping how to'), O.tongue, 'oral'),
    /* ---- the mind, the desk, the page ---- */
    g('lightson', /lights on/i, 'Lights on · big water',
      ['Brightest light in reach the second you sit up', 'Then the whole glass', 'Light tells the clock the night is over', 'No phone until both are done'],
      'Reaching for the phone first — light and water, then the world', yt('morning light and hydration routine'), O.bright, 'mind'),
    g('water', /^water|the whole glass|gakid\u014d|hunger/i, 'The whole glass',
      ['The largest glass you own, filled', 'Drink all of it, standing, before anything else', 'It ends the night dehydration and starts the engine', 'Easiest step in the app. Take the win'],
      'A sip — the whole thing', yt('why drink water first thing in the morning'), O.glass, 'mind'),
    g('daylight', /daylight/i, 'Ten minutes of daylight',
      ['Outside — a window does not count', 'No sunglasses; don\u2019t stare at the sun', 'Within the first hour of waking', 'Overcast still works; stay longer'],
      'Doing it through glass — the dose drops to almost nothing', yt('morning sunlight circadian rhythm'), O.sun, 'mind'),
    g('outside', /step outside|kunai down/i, 'Step outside — two minutes of sky',
      ['Stand up; leave the screen behind', 'Two minutes outside, or at an open window', 'Look far; let the eyes rest', 'Water. Then back to the mark'],
      'Scrolling during the break — the break is the absence of the screen', yt('microbreak outside focus'), O.outside, 'mind'),
    g('focus', /flying raijin|strike two/i, 'The strike — one thing, nothing else',
      ['One document open. Phone in another room', 'Timer running; the mark is the only task', 'If the mind wanders, write the thought on paper and return', 'Stop when the timer stops — even mid-sentence'],
      'Checking \u201cjust one thing\u201d — every check restarts the climb', yt('deep work focus block'), O.desk, 'mind'),
    g('clearfield', /clear the field|cut the feed|phone exiled|in bed/i, 'Clear the field — the phone leaves',
      ['Phone in another room, charging', 'Every tab closed except one', 'Nothing glowing in reach', 'The field is clear when nothing can interrupt'],
      'Face-down on the desk — that\u2019s still in reach', yt('phone free focus sleep'), function () { return O.phone(); }, 'mind'),
    g('target', /mark the target/i, 'Mark the target — the one task',
      ['One line: the single task that makes today a win', 'Not three. One', 'Write it where you\u2019ll see it all morning', 'Everything else waits behind it'],
      'A to-do list — this is one target, not a list', yt('most important task morning'), O.target, 'mind'),
    g('targets', /three targets|one certainty|declare tomorrow|the vow$|log the vow/i, 'The written line',
      ['Pen and paper beat the phone here', 'Specific beats poetic — name the thing', 'Short is complete; long is hiding', 'Leave it where you\u2019ll see it'],
      'Writing what sounds good instead of what is true', yt('daily intention journaling'), function () { return O.journal(); }, 'mind'),
    g('ledger', /face the ledger/i, 'Face the ledger',
      ['Open the day: what was promised, what was delivered', 'Two columns. No commentary, no excuses', 'The gap is the debt — count it', 'Close the book; the push-ups pay it'],
      'Explaining the gaps — the ledger records, it doesn\u2019t argue', yt('daily review journal accountability'), O.ledger, 'mind'),
    g('journal', /journal|three lines|seal the progress|jigokud\u014d|brain dump|gourd empties|kai —|name three|kindness/i, 'The written step — three honest lines',
      ['What happened. What mattered. What tomorrow needs', 'Specific beats poetic', 'Three lines is complete; ten is hiding', 'Tomorrow-you is the reader. Be useful to them'],
      'Skipping it because nothing happened — that\u2019s a line', yt('three line journal habit'), function () { return O.journal(); }, 'mind'),
    g('read', /read paper|paper over glass|ningend\u014d/i, 'Ten minutes with a physical book',
      ['Any book. Paper, not a screen', 'Ten minutes by the clock', 'If the mind drifts, re-read the paragraph; that\u2019s fine', 'Close it at the timer — the habit is the point'],
      'Reading on a phone — the glow is what you\u2019re avoiding', yt('reading before bed benefits'), O.book, 'mind'),
    g('debt', /the debt/i, 'The debt — ten per broken promise',
      ['Count today\u2019s broken promises honestly', 'Ten push-ups each, strict', 'Pay now, not tomorrow', 'Zero broken? Ten anyway — the ledger stays open'],
      'Negotiating the count', L.pushup, P.pushupFail),
    g('purge', /the purge/i, 'The purge — one thing leaves',
      ['Delete one app, unfollow one account, or clear one drawer', 'One. Not a reorganization', 'Do it now, in the three minutes', 'Notice how little you miss it tomorrow'],
      'Making a list of things to purge — that is not purging', yt('digital declutter one thing'), O.delete, 'mind'),
    g('mirror', /mirror vow/i, 'The mirror vow',
      ['Face the mirror. Eyes on your own eyes', 'Say the vow out loud — no mumbling', 'Hold the gaze three seconds after', 'Leave'],
      'Saying it to the floor', yt('mirror affirmation practice'), O.mirror, 'mind'),
    g('gratitude', /gratitude/i, 'Gratitude, loudly',
      ['One thing. Specific', 'Out loud, full voice', 'To the room, or to someone', 'Move on — it doesn\u2019t need a second one'],
      'Mumbling — the loudness is the practice', yt('gratitude out loud practice'), function () { return O.speak('one thing, full voice'); }, 'mind'),
    g('caffeine', /caffeine/i, 'Caffeine after, not before',
      ['Water first, always', 'Coffee 60–90 minutes after waking', 'Let the natural cortisol wave crest and fall first', 'Earlier and it lands on top of the wave — later it works'],
      'Coffee in the first fifteen minutes — it steals from the afternoon', yt('delay caffeine after waking'), O.coffee, 'mind'),
    g('kitchen', /kitchen closed/i, 'Kitchen closed',
      ['Last real food two to three hours before bed', 'Water and herbal tea are fine', 'Digestion and deep sleep compete — give sleep the field', 'Hungry? Note it; morning comes fast'],
      'A late snack \u201cto help sleep\u201d — it fragments it', yt('eating before bed sleep quality'), O.kitchen, 'mind'),
    g('lightslow', /lights low|early lights/i, 'Lights low · screens warm',
      ['Overheads off; lamps only', 'Night mode on every screen', 'Dim tells the clock the day is ending', 'Tonight, earlier than usual'],
      'A bright bathroom light at the end — keep even that dim', yt('dim lights before bed melatonin'), O.lamp, 'mind'),
    g('clock', /clock faces/i, 'Clock faces the wall',
      ['Turn every clock away', 'Phone in another room', 'You will not negotiate with numbers tonight', 'If you wake, don\u2019t look'],
      'Checking \u201cjust once\u201d — every check is math, and math is awake', yt('clock watching insomnia'), O.clock, 'mind'),
    g('cave', /cool the desert|the cave/i, 'The cave — 65–68°F, blackout, silence',
      ['Thermostat to 65–68°F if you can', 'Blackout dark — cover every LED', 'Silent, or steady noise', 'Nothing glowing'],
      'One small LED left on — cover it', yt('ideal bedroom temperature for sleep'), P.thermostat, 'mind'),
    g('layout', /lay out tomorrow/i, 'Lay out tomorrow',
      ['Clothes, bag, water — set where you\u2019ll trip over them', 'Tomorrow\u2019s first step already decided', 'Two minutes now saves the morning', 'The sand settles'],
      'Doing it \u201cin your head\u201d — physical, visible, in the way', yt('prepare the night before routine'), O.laidOut, 'mind'),
    g('anchor', /anchor —/i, 'The anchor — feet on the floor',
      ['Same wake time ±30 minutes, weekends included', 'Feet on the floor before the snooze exists', 'Sit up, stand up, lights on', 'The anchor sets every clock behind your eyes'],
      'The weekend sleep-in — it drags every clock two hours back', yt('consistent wake time sleep'), O.feet, 'mind'),
    g('cold', /cold/i, 'The cold finish — thirty honest seconds',
      ['Last thirty seconds of the shower, full cold', 'Exhale first, then turn the dial — no bracing', 'Breathe slow through it; the gasp passes', 'When it bites, ten more seconds. Step out awake'],
      'Holding the breath — slow exhale beats the gasp', L.cold, P.coldShower, 'mind'),
    g('warm', /warm rinse/i, 'Warm rinse — heat on the tight spots',
      ['Two minutes of warm water on today\u2019s report', 'Let the muscle soften under it', 'Slow breathing; shoulders down', 'Dry off; straight to the early lights'],
      'Too hot — it wakes you up instead', yt('warm shower before bed'), P.warmShower, 'mind'),
    g('choosepath', /choose the path/i, 'The path slot',
      ['Your character path runs here', 'No time today? Skip it and keep the chain', 'A path sealed seven times is mastered', 'Mastery at Jōnin unlocks the Released forms'],
      'Skipping the base because there\u2019s no time for the path — the base is the chain', null, function () { return O.checkmark('the base seals the day either way'); }, 'mind'),
    g('bed', /bed/i, 'In bed — same time every night',
      ['Same time, every night', 'Phone charging in another room', 'Dark, cool, quiet', 'Done means done'],
      'One more scroll — that\u2019s the whole night gone', yt('consistent bedtime benefits'), P.bed, 'mind'),
    g('generic', /./, 'Do it properly, then stamp it',
      ['Read the cue once before you start', 'Do the whole step, not the version that fits', 'If you cannot do it today, skip is honest', 'Stamp only what actually happened'],
      'Stamping the intention instead of the act', null, function () { return O.checkmark('the whole step, then the stamp'); }, 'mind')
  ];

  var byId = {}; G.GUIDES.forEach(function (x) { byId[x.id] = x; });
  /* find the guide for a step: explicit id wins, then the name matcher */
  G.guideFor = function (m) {
    if (!m || m.guide === 'none' || m.type === 'section' || m.type === 'path') return null;
    if (m.guide && byId[m.guide]) return byId[m.guide];
    var name = m.name || '';
    for (var i = 0; i < G.GUIDES.length; i++) { if (G.GUIDES[i].rx.test(name)) return G.GUIDES[i]; }
    return null;
  };
  G.guideById = function (id) { return byId[id] || null; };
  G.guideSVG = function (gd) { try { return svg(gd.draw()); } catch (e) { return ''; } };
  G.curatedFor = function (m) { var gd = G.guideFor(m); return gd && gd.link ? gd.link : null; };
  G.stepHasHelp = function (m) { return !!(G.guideFor(m) || (m.ref && m.ref.url) || m.img); };
})((typeof window !== 'undefined' ? window : global).HOKAGE = (typeof window !== 'undefined' ? window : global).HOKAGE || {});
